### PR TITLE
feat: pass sentry instance

### LINKED ISSUE #41: Pass Sentry instance
#### How it works now and why this is problematic
Currently it's only possible to pass a Sentry configuration and `graphq-middleware-sentry` will initialize the Sentry instance on its own. This behaviour is suboptimal, if we want to re-use a sentry instance in other places with the same configuration, for example to manually capture certain errors, without throwing in the resolver.

Also if you install the newest version of Sentry and keep your modules up to date, `graphql-sentry-middleware` will always lag behind your version of Sentry. **Which will result in two versions of sentry in your `node_modules`!** This also raises the question, whether Sentry could be a peer dependency.

#### The current workaraound:
```js
// some config file
const sentryConfig = {
          dsn: process.env.SENTRY_DSN,
          environment: process.env.NODE_ENV,
        // ... much more config
        }
// ...

// createSentryMiddleware.ts
import { sentryConfig } from "./sentryConfig";

sentry({
        config: sentryConfig,
});
// ...

// Sentry.ts
import * as Sentry from "@sentry/node";
import { sentryConfig } from "./sentryConfig";


Sentry.init({
  dsn: process.env.SENTRY_DSN,
});

export { Sentry };
```

### PR DESCRIPTION
**Pull request by herkulano**
Closes #41

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
I'm still thinking about this suggestion, definitely like it but shouldn't we make it optional for apps that don't use Sentry in other places, so creating a Sentry object if it's not supplied and using the supplied one if it exists? I do agree to use a solution like a peerDependency to prevent versioning issues between the middleware and the consuming app, maybe we could add that as well.

**Comment by herkulano** [comment]
@BrunoScheufler I agree, I can make those changes this weekend.

**Comment by herkulano** [comment]
@BrunoScheufler yes, but at some point, it would be good to have tests to make sure everything works before publishing.

**Comment by BrunoScheufler** [comment]
@herkulano thought of that as well, especially for the future.. will look into that!

**Pull request merged**
